# Generated by Django 3.2.25 on 2024-05-26 13:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LastProducts',
            fields=[
                ('products_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('image_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.PositiveIntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='ID_Telegram')),
                ('username', models.CharField(blank=True, max_length=150, verbose_name='Username')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('products_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('description', models.TextField(max_length=2500)),
                ('image_url', models.URLField(blank=True)),
                ('discount', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'unique_together': {('name', 'price')},
            },
        ),
    ]
