# Generated by Django 3.2.25 on 2024-05-25 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
